project:
  type: website
  output-dir: docs

execute:
  freeze: true

website:
  title: "Big 30"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - movies.qmd
  favicon: ./static/cake.svg
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



